### ISSUE TITLE
Review sendmail vulnerabilities

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#119]
https://framework.zend.com/security/advisory/ZF2016-04
https://github.com/PHPMailer/PHPMailer/wiki/About-the-CVE-2016-10033-and-CVE-2016-10045-vulnerabilities
https://github.com/LimeSurvey/LimeSurvey/pull/616

**Comment by jvangestel** [comment]
Since we have selectable FROM in at least the token mailer, we'll have to update the email validator used for organizations and users to be sure we use correct E-mail addresses. 

In the token mailer an E-mail address can't be injected in the mail form itself.

In the communication template editor you are able to manually change the E-mail address. So this will need to use the new validator as well.

**Comment by mddejong** [comment]
Have fixed the issue by changing the e-mail validator: `backtik is no longer allwoed in e-mail name.
