### ISSUE TITLE
Changing track field type to appointment is impossible

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#169]
When changing a saved but unused track field from any type to appointment (and NOT selecting a filter), the save will result in a database error:
Mysql statement execute error: Column 'gtap_min_diff_length' cannot be null

**Comment by mennodekker** [comment]
As this is only a problem in rare conditions, changed priority to low. Evaluate for next version, don't hold back current release for this.

**Comment by mddejong** [comment]
This is not a bug, but a feature of the design. 

If you would change any field to type appointment all existing values would be void. Instead of changing the type you can throw away the current field and make a new appointment field. If, to fill those appointments, you need the old field, then both fields have to co-exist for a while anyway.
