### ISSUE TITLE
Update externals in templates to recent versions

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#193]
We are using older versions of jquery, bootstrap, font-awesome and the ck-editor. 

Check to see if we can upgrade, maybe even use components to make the whole process easier and more independent of the used template. Because of the deep-integration we have with linking to all the files this is a change that can break a lot of the visual stuff so best to wait for 1.8.3

**Comment by mennodekker** [comment]
https://asset-packagist.org/

**Comment by mddejong** [comment]
This update caused a lot of items to stop working: 

- the tabbed forms seem to work initially but do not work when actually being used
- the add track dropdown no longer works
- some batches refuse to run - in particular the patches batch.

Either we need to fix these issues or drop back to older versions.

**Comment by mddejong** [comment]
OK gave up on Bootstrap 4, caused the above issues minus the batch issue (this is fixed in MUtil)

Keeping on trying to use newest jQuery. Lets check this link for possible issues: https://api.jquery.com/category/deprecated/

Furthermore we need a new CK editor version, though this one seems to keep working.
